### ISSUE TITLE
ImportError: cannot import name 'cached_property'

### ISSUE THREAD

**Issue by avimehenwal** [CN-UPB/tng-sdk-benchmark#108]
```sh
(venv) avi@fgcn-backflip2:~/tng-sdk-benchmark$ cat error_chached_property.log 
(venv) avi@fgcn-backflip2:~/tng-sdk-benchmark$ tng-bench --help
Traceback (most recent call last):
  File "/home/avi/tng-sdk-benchmark/venv/bin/tng-bench", line 11, in <module>
    load_entry_point('tngsdk.benchmark==5.0.0', 'console_scripts', 'tng-bench')()
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/tngsdk.benchmark-5.0.0-py3.6.egg/tngsdk/benchmark/__init__.py", line 45, in <module>
    from tngsdk.benchmark.generator.tango \
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/tngsdk.benchmark-5.0.0-py3.6.egg/tngsdk/benchmark/generator/tango.py", line 39, in <module>
    import tngsdk.package as tngpkg
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/tngsdk.package-5.1-py3.6.egg/tngsdk/package/__init__.py", line 36, in <module>
    from tngsdk.package import rest, cli
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/tngsdk.package-5.1-py3.6.egg/tngsdk/package/rest.py", line 38, in <module>
    from flask_restplus import Resource, Api, Namespace
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/flask_restplus-0.13.0-py3.6.egg/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/home/avi/tng-sdk-benchmark/venv/lib/python3.6/site-packages/flask_restplus-0.13.0-py3.6.egg/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'

(venv) avi@fgcn-backflip2:~/tng-sdk-benchmark$ 

```

**Comment by avimehenwal** [comment]
Problem seems to be at 

`src/tngsdk/benchmark/__init__.py` `line 45`

```python
import tngsdk.package as tngpkg
```

**Comment by avimehenwal** [comment]
Works well ONLY with older version on `Werkzeug` package
